### ISSUE TITLE
horizontalni scroll

### ISSUE THREAD

**Issue by nticaric** [teamtnt/sales-management#4]
hvatati ondrag event, i pratiti poziciju mouse cursora. kada je na 20% desne strane, napraviti horizontalni scroll prema desno, ne prevelikom brzinom

isto tako hvatati cursor an 10% donjeg dijela ekrana i ubaciti vertical scroll

**Comment by stokic** [comment]
btw grab tab and swiping works to the right, but still not to the top or left side.

**Comment by TomePale** [comment]
Done.
